version: '3.8'

services:
  pipevideo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pipevideo
    restart: always
    env_file:
      - .env
    networks:
      - epitnet_internal

networks:
  epitnet_internal:
    external: true
    name: epitnet_internal
