#!/bin/sh
set -e

# public/ is mounted as a persistent volume so generated assets (scene_*.mp4/mp3/png,
# .last_rendered_id) survive container restarts/rebuilds instead of forcing Novita/TTS
# to regenerate everything (and burn API credits) on every deploy.
# Because a named volume is EMPTY on its very first mount, this restores the
# git-tracked static assets (public/sounds/, .gitkeep) from the image into the
# volume once, without ever overwriting files already generated by a previous run.
if [ ! -d /app/public/sounds ]; then
  echo "[Entrypoint] Seeding public/ with static assets from the image (first run on this volume)..."
  cp -rn /app/.image-public/. /app/public/
fi

exec "$@"
